# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Shorten-Digg
version:      0.01
version_from: lib/WWW/Shorten/Digg.pm
installdirs:  site
requires:
    HTML::Entities:                0
    URI::Escape:                   0
    WWW::Shorten:                  1.98

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
